### ISSUE TITLE
installing 047-nrpe on ubuntu/debian error

### ISSUE THREAD

**Issue by Xelo** [Cat5TV/nems-admin#2]
Hi,
as mentioned, if I am trying to install the nrpe package on an Client via 

`wget -O - https://raw.githubusercontent.com/Cat5TV/nems-admin/master/build/047-nrpe | bash`

it wont work without "build-essential" maybe a check if it is installed or an information that it is needed would be helpful.

Best,
Zerant aka Xelo

**Comment by Cat5TV** [comment]
Thank you for pointing this out. I always think of nems-admin in the context of NEMS Linux, and of course within NEMS Linux _build-essential_ was already installed during the build process. I have committed the fix. Please re-try the installer and let me know how it goes.
