### ISSUE TITLE
Wrong path to plugins in the nrpe.cfg

### ISSUE THREAD

**Issue by Xelo** [Cat5TV/nems-admin#3]
Hi,
As mentioned on Discord, if you use the `wget -O - https://raw.githubusercontent.com/Cat5TV/nems-admin/master/build/047-nrpe | bash` to install nrpe the path to the plugins in the nrpe.cfg on Ubuntu are wrong.

They are at `/usr/local/nagios/libexec/check_users` and should point to `/usr/lib/nagios/plugins/check_users`.

Best,
Zerant aka Xelo

**Comment by Cat5TV** [comment]
This should be resolved. Please re-run the installation script [as per the NEMS Linux documentation](https://docs.nemslinux.com/usage/nrpe_on_linux), and let me know.
