### ISSUE TITLE
Check WMIC Issues on NEMS 1.6 Beta

### ISSUE THREAD

**Issue by GitMarshallBill** [Cat5TV/nems-admin#6]
![Screenshot_2021-06-02_16-26-23](https://user-images.githubusercontent.com/7557539/120647380-8bf96980-c448-11eb-8d65-e43170b94d76.png)

Ran `sudo apt install libnumber-format-perl and the faults went away

Better if you check it out. Alpha release not exhibiting the issue

**Comment by Cat5TV** [comment]
Thanks @GitMarshallBill - I have added the dependency. A _nems-update_ will implement the fix.
